### ISSUE TITLE
git sources are not being run

### ISSUE THREAD

**Issue by lukeorland** [spencergibb/battleschool#21]
My config.yml file currently looks like this, and no playbooks from either of the sources under `git:` are being run:

```
---
cache_dir: ~/Library/Caches/battleschool

sources:
#local:
#  - playbook.yml

#url:
#  - name: playbook.yml
#    url: https://db.tt/VcyI9dvr

  git:
    - name: osx
      repo: 'https://github.com/spencergibb/ansible-osx'
      playbooks:
         #- adium.yml
         #- alfred.yml
         #- better-touch-tool.yml
         - chrome-stable.yml
         #- chrome-beta.yml
         - dropbox.yml
         #- github.yml
         - homebrew.yml   # must come before any use of homebrew module
         #- intellij-idea-ultimate.yml
         #- intellij-idea-ultimate13.yml
         - iterm2.yml
         #- java6.yml
         - java7.yml
         #- libreoffice.yml
         #- macports.yml  # must come before any use of macports module
         #- macvim.yml
         #- sequel-pro.yml
         - skype.yml
         - truecrypt.yml
         - usb-overdrive.yml
         - virtualbox.yml
         - vagrant.yml
         - virtualbox.yml
         #- xtra-finder.yml

    - name: my-env
      repo: 'https://github.com/lukeorland/battleschool-myenv'
      playbooks:
        - playbook-mac.yml
```

The command:

    battle --config-file https://raw.githubusercontent.com/lukeorland/battleschool-myenv/master/config-mac.yml -K

The output: 

```
sudo password:
## Updating sources ##############################################################################################
	Task OK: git
	Task OK: git
	WARNING: no playbooks run!
## Battleschool completed ########################################################################################
```
