### ISSUE TITLE
support ansible version 1.9.x

### ISSUE THREAD

**Issue by RaviH** [spencergibb/battleschool#25]
System Information:
================
Mac - 10.10.2
Python - 2.7.5 / 2.7.6 

config.yml
===
```
---
cache_dir: ~/Library/Caches/battleschool

sources:
#  local:
#    - playbook.yml

  url:
    - name: playbook.yml
      url: https://db.tt/VcyI9dvr

  git:
    - name: 'osx'
      repo: 'https://github.com/spencergibb/ansible-osx'
      playbooks:
         - homebrew.yml                 #must come before any use of homebrew module
```

Error
=======
(python-2.7.5)kapasdevmac12fm:~ rhasija$ battle 
Traceback (most recent call last):
  File "/usr/local/bin/battle", line 7, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Library/Python/2.7/site-packages/battleschool/main.py", line 95, in main
    help="set additional key=value variables from the CLI")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1020, in add_option
    self._check_conflict(option)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 995, in _check_conflict
    option)
optparse.OptionConflictError: option -e/--extra-vars: conflicting option string(s): -e, --extra-vars
(python-2.7.5)kapasdevmac12fm:~ rhasija$
