### ISSUE TITLE
OSX Defaults

### ISSUE THREAD

**Issue by patrickheeney** [spencergibb/battleschool#3]
Would it be possible to build a ansible module for osx defaults similar to the mac_pkg. It would look something like:

```
name: Enable dock autohide
mac_default: >
  key=autohide
  domain=com.apple.dock
  value=true
  type=bool
  user={{ ansible_ssh_user }}
  state=present

name: Set the icon size of Dock items to 50 pixels
mac_default: >
  key=tilesize
  domain=com.apple.dock
  value=50
  type=int
  user={{ ansible_ssh_user }}
  state=present
```

This would run the code similar to https://github.com/boxen/puppet-boxen/blob/master/manifests/osx_defaults.pp in boxen / puppet. I don't know python but I would be happy to contribute a bunch of playbooks using the new options. 

The default playbooks could consist of https://github.com/ndhoule/my-boxen/tree/master/modules/osx_config/manifests which is similar to ones I used to use and could be included like so:

```
- name: 'osx-defaults'
  repo: 'https://github.com/spencergibb/ansible-osx-defaults'
  playbooks:
    - animations
    - dashboard
    - terminal
```
