### ISSUE TITLE
`pip`  doesn't respect `chdir=` under battleschool?

### ISSUE THREAD

**Issue by subsetpark** [spencergibb/battleschool#32]
I've got a playbook being called under `local` with a command that looks like this:

```yaml
    - name: install site requirements
      sudo: no
      pip: chdir=~/src/ requirements=~/src/requirements.txt virtualenv=~/env
```
And it fails with an error like this:
```python
IOError: [Errno 2] No such file or directory: '/Users/dev/.battleschool/playbooks/ext/src/bundled-package.zip'
```

This is because, among other things, my requirements.txt includes a line './ext/src/bundled-package.zip', where `ext` is a directory in the `~/src/` directory. So normally `chdir` should set the correct operating directory such that the package could be found. A command of this form works just fine in a normal ansible playbook that I use to deploy.
