### ISSUE TITLE
vars_prompt not prompting

### ISSUE THREAD

**Issue by OldhamMade** [spencergibb/battleschool#39]
I've tried the following config:
```yaml
---
cache_dir: ~/Library/Caches/battleschool
sources:
  url:
    - name: setup.yml
      url: 'https://www.dropbox.com/s/1234567890/setup.yml?dl=1'
```
and setup.yml:
```yaml
---
- hosts: workstation
  vars_prompt:
    - name: "some_password"
      prompt: "Enter password"
      private: yes
  tasks:
    ...
```
but I'm not being prompted when running battleschool as follows:
`battle -XKvv --config-file=~/.battle/config.yml --become-user=$USER`
